apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-plot
  labels:
    app: homelab-plot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homelab-plot
  template:
    metadata:
      labels:
        app: homelab-plot
    spec:
      containers:
      - name: homelab-plot
        image: danhigham/homelab-plot:latest
        ports:
        - containerPort: 8080
        env:
        - name: BOSH_ADDRESS
          value: https://10.0.0.10:25555
        - name: BOSH_CLIENT
          value: homelab-plot
        - name: BOSH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: bosh-secret
              key: value
        - name: VCENTER_URI
          valueFrom:
            secretKeyRef:
              name: vcenter-uri
              key: value
---
kind: Service
apiVersion: v1
metadata:
  name: homelab-plot-http
spec:
  type: NodePort
  selector:
    app: homelab-plot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

